### ISSUE TITLE
Crash in PWInAppMessagesManager setEmails:completion:]_block_invoke ()

### ISSUE THREAD

**Issue by sashkyn** [Pushwoosh/pushwoosh-ios-sdk#104]
Hello. We have a crash when app is starting.
When we comment 
> Pushwoosh.sharedInstance().setEmail("email@example.com") 

app stop crashing.
Xcode screenshot:
<img width="2546" alt="image" src="https://user-images.githubusercontent.com/14783903/152777926-1027398c-078c-4e3f-8c03-d1be9c82e9d0.png">

**Comment by wfhm** [comment]
@sashkyn got it reproduced, the fix will be rolled out shortly.

**Comment by wfhm** [comment]
Fixed in 6.3.4.
