### ISSUE TITLE
Build fails on M1 due to linking error

### ISSUE THREAD

**Issue by taschik** [Pushwoosh/pushwoosh-ios-sdk#105]
Hi, 
I am trying to build our app using the pushwoosh iOS library on a new MacBook Pro with M1Max but am receiving the following error when building on a simulator:

```
ld: in /Users/user/Documents/app/app-mobile/ios/Pods/Pushwoosh/Framework/Pushwoosh.framework/Pushwoosh(libPushwoosh.a-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/user/Documents/app/app-mobile/ios/Pods/Pushwoosh/Framework/Pushwoosh.framework/Pushwoosh'
```

Our architecture config in Xcode looks like this:
<img width="696" alt="Screen Shot 2022-02-09 at 4 35 10 PM" src="https://user-images.githubusercontent.com/351623/153314320-8556b8bc-ab55-4503-80a4-44468a344876.png">

The build works great when building for a device but not for simulator. Any idea why this would be?

**Comment by RaimundasSakalauskas** [comment]
Same issue here.

**Comment by wfhm** [comment]
@taschik @RaimundasSakalauskas 

Regular Pushwoosh.framework does not include architectures used on M1 simulators, so apps with Pushwoosh SDK on M1 devices should use the .xcframework as a dependency. Your Podfile should add Pushwoosh SDK like this:
```
pod 'PushwooshXCFramework`
```

**Comment by taschik** [comment]
Thank you @wfhm. I worked around it by running everything with Rosetta2 for now.
