### ISSUE TITLE
[question] Pushwoosh and PushwooshXCFramework versions on CocoaPods

### ISSUE THREAD

**Issue by awoczek** [Pushwoosh/pushwoosh-ios-sdk#107]
I have a question why do you provide two versions of the same library? Why you distribute separately podspec for xcframework and universal framework? Is it only for old Xcode compatibility or there is other reason? What is difference and what version should i use for iOS app?

**Comment by wfhm** [comment]
@awoczek 

The main reason for us to keep both .xcframework and .framework is that Pushwoosh SDK is used in our cross-platform plugins, and not all of them were migrated to .xcframework yet, and some of them just cannot be migrated to it, so we have to keep the old format to avoid compatibility issues.
