### ISSUE TITLE
Unable to get message_id from remote push

### ISSUE THREAD

**Issue by vaqueromena** [Pushwoosh/pushwoosh-ios-sdk#108]
Hi all,
Could you explain me how to get message_id (push_id) for opened/ received push?

**Comment by wfhm** [comment]
@vaqueromena 

Do you mean the Notification ID from the Message History in the Control Panel? If so, there is no dedicated method to get this data as this ID is designed to only be used internally. However, you can still get it from the "metadata" dictionary from the payload of a push in `onPushAccepted:` and/or `onPushReceived:` callbacks:

```
- (void)onPushAccepted:(PushNotificationManager *)pushManager withNotification:(NSDictionary *)pushNotification onStart:(BOOL)onStart {
    NSString* uid = [[pushNotification objectForKey:@"md"] objectForKey:@"uid"];
...
}
```

**Comment by vaqueromena** [comment]
Thank you @wfhm
