### ISSUE TITLE
Not getting remote notification in debug mode

### ISSUE THREAD

**Issue by ishteyaque06** [Pushwoosh/pushwoosh-ios-sdk#109]
I am not getting remote push notification when installing app directly from Xcode(debug mode). When I create an ipa and installing it then it start working.
I have also tried to register device as Test device, but no luck.

**Comment by Techsorcist** [comment]
@ishteyaque06, are you using an iPhone device for testing notifications or the iOS simulator? Notifications don't work on a simulator by design, so you must be using an actual Apple device, secondly your notification hub must be set up in "sandbox" mode.

**Comment by ishteyaque06** [comment]
I am using actual device. Need help to setup snadbox mode

**Comment by Techsorcist** [comment]
@ishteyaque06 may I ask you to contact PW support team at help@pushwoosh.com with your account name and share them logs (in txt format) from Xcode to troubleshoot it further?
