### ISSUE TITLE
Pushwoosh in Background could lead to termination

### ISSUE THREAD

**Issue by dungi** [Pushwoosh/pushwoosh-ios-sdk#110]
In Xcode14 I get following error:

`[BackgroundTask] Background Task 3 ("Called by Pushwoosh, from -[PWRequestManager sendRequest:completion:]"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.`

What task should I terminate in background?

**Comment by wfhm** [comment]
@dungi Hi, sorry for such a delayed response!

You should have nothing to worry about - we do call `endBackgroundTask` in our SDK, so there should be no additional actions from your side.
