### ISSUE TITLE
Pushwoosh_PURCHASE_TRACKING_ENABLED crashes on version 6.4.9

### ISSUE THREAD

**Issue by ARFAOUI** [Pushwoosh/pushwoosh-ios-sdk#111]
I know this is supposed to be fixed in version 6.4.9
<img width="260" alt="Screenshot 2023-01-19 at 22 39 55" src="https://user-images.githubusercontent.com/1867492/213569506-81186ce2-3c21-4bee-aaa0-516773602543.png">
but once I add the flag to the plist it crashes the app.

Swift Package Manager 
Pishwoosh SDK: 6.4.9

scenario 1: Device environment:
Model:iPhone XR
iOS Version:16.2.0
Orientation: Portrait

crashlytics report:

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x9e48 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw
2  CoreFoundation                 0x17e82c +[NSObject(NSObject) _copyDescription]
3  CoreFoundation                 0x1ff60 ___forwarding___
4  CoreFoundation                 0x88330 _CF_forwarding_prep_0
5  TikDown                        0xb9dc38 specialized _PaymentObserver.paymentQueue(_:updatedTransactions:) + 70 (_PaymentObserver.swift:70)
6  TikDown                        0xb9da50 @objc _PaymentObserver.paymentQueue(_:updatedTransactions:) (<compiler-generated>)
7  Pushwoosh                      0x16554 (Missing UUID f5c51b2110fc3e7983aa5f6328494ea8)
8  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release
9  libdispatch.dylib              0x3fdc _dispatch_client_callout
10 libdispatch.dylib              0x127f4 _dispatch_main_queue_drain
11 libdispatch.dylib              0x12444 _dispatch_main_queue_callback_4CF
12 CoreFoundation                 0x9a6d8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
13 CoreFoundation                 0x7c03c __CFRunLoopRun
14 CoreFoundation                 0x80ec0 CFRunLoopRunSpecific
15 GraphicsServices               0x1368 GSEventRunModal
16 UIKitCore                      0x3a186c -[UIApplication _run]
17 UIKitCore                      0x3a14d0 UIApplicationMain
18 TikDown                        0x7768 main + 30 (AppDelegate.swift:30)
19 ???                            0x1d8866960 (Missing)

scenario 2: Xcode 14.2 / Simulator Crash report 

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[APMAnalytics createRequestorWithTransaction:]: unrecognized selector sent to instance 0x6000006e46f0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000018040e7c8 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180051144 objc_exception_throw + 56
	2   CoreFoundation                      0x000000018041d47c +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00000001804126c8 ___forwarding___ + 1308
	4   CoreFoundation                      0x0000000180414b4c _CF_forwarding_prep_0 + 92
	5   TikDown                             0x000000010467cabc $s12FBSDKCoreKit16_PaymentObserverC12paymentQueue_19updatedTransactionsySo09SKPaymentF0C_SaySo0I11TransactionCGtFTf4dnn_n + 204
	6   TikDown                             0x000000010467c8d4 $s12FBSDKCoreKit16_PaymentObserverC12paymentQueue_19updatedTransactionsySo09SKPaymentF0C_SaySo0I11TransactionCGtFTo + 104
	7   Pushwoosh                           0x000000010db716d8 _replacement_paymentQueueUpdatedTransactions + 72
	8   libdispatch.dylib                   0x000000010eab0594 _dispatch_call_block_and_release + 24
	9   libdispatch.dylib                   0x000000010eab1d5c _dispatch_client_callout + 16
	10  libdispatch.dylib                   0x000000010eac2808 _dispatch_main_queue_drain + 1316
	11  libdispatch.dylib                   0x000000010eac22d4 _dispatch_main_queue_callback_4CF + 40
	12  CoreFoundation                      0x0000000180372ca4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
	13  CoreFoundation                      0x000000018036d360 __CFRunLoopRun + 1956
	14  CoreFoundation                      0x000000018036c7a4 CFRunLoopRunSpecific + 584
	15  GraphicsServices                    0x0000000188ff7c98 GSEventRunModal + 160
	16  UIKitCore                           0x0000000112b0237c -[UIApplication _run] + 868
	17  UIKitCore                           0x0000000112b06374 UIApplicationMain + 124
	18  TikDown                             0x00000001023d33f0 main + 64
	19  dyld                                0x000000010dc3dfa0 start_sim + 20
	20  ???                                 0x000000010d96508c 0x0 + 4522922124
	21  ???                                 0xf44e000000000000 0x0 + 17604007993437847552
)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[APMAnalytics createRequestorWithTransaction:]: unrecognized selector sent to instance 0x6000006e46f0'
terminating with uncaught exception of type NSException
CoreSimulator 857.14 - Device: iPhone 14 (E05A39C6-D24C-4B03-A19E-B5A5F80BDCB8) - Runtime: iOS 16.2 (20C52) - DeviceType: iPhone 14

**Comment by wfhm** [comment]
@ARFAOUI Checking it.

**Comment by akiselev-pushwoosh** [comment]
@ARFAOUI Hello! We fixed this bug in Pushwoosh iOS SDK v. 6.4.10. If you'll have some problems let us know
