### ISSUE TITLE
Apple M1/M2 Support

### ISSUE THREAD

**Issue by FilippoDev** [Pushwoosh/pushwoosh-ios-sdk#112]
Hello, could you please add M1 arch support for the pod?
Currently, the build fails with the following error:
Building for iOS Simulator, but linking in object file built for iOS

I tried also the latest version 6.4.10

Thanks.

**Comment by akiselev-pushwoosh** [comment]
@FilippoDev Hello! Are you using pod 'PushwooshXCFramework'?

**Comment by FilippoDev** [comment]
@akiselev-pushwoosh I am using installation via cocoapods and at this moment it doesn't work
as I explained in the previous message. If I use a real device it works otherwise not.

**Comment by akiselev-pushwoosh** [comment]
@FilippoDev I mean use pod 'PushwooshXCFramework' in your podfile instead of pod 'Pushwoosh'. XCFramework supports M1/M2 chips

**Comment by FilippoDev** [comment]
do you mean this one https://github.com/Pushwoosh/Pushwoosh-XCFramework based on swift?

**Comment by akiselev-pushwoosh** [comment]
@FilippoDev No, it Swift Package Manager. 

If you are using integration via cocoapods your Podfile should looks like this:

`# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demoapp
  pod 'PushwooshXCFramework'

end`

**Comment by FilippoDev** [comment]
ok thanks the same library but other framework, thanks for explanation 💯
