### ISSUE TITLE
setTags generates warnings to console

### ISSUE THREAD

**Issue by vitalii-noname** [Pushwoosh/pushwoosh-ios-sdk#113]
Hello,

The setTags function generates warnings to console
SDK 6.5.0

Steps. to reproduce:

- enable the All Runtime Issues breakpoint and
- send any dictionary: `Pushwoosh.sharedInstance().setTags([tag: value])`

in console:
`[general] *** -[NSKeyedUnarchiver validateAllowedClass:forKey:] allowed unarchiving safe plist type ''NSString' (0x1f2ceafd8) [/System/Library/Frameworks/Foundation.framework]' for key 'NS.objects', even though it was not explicitly included in the client allowed classes set: '{(
    "'NSDictionary' (0x1f2ce3648) [/System/Library/Frameworks/CoreFoundation.framework]",
    "'NSArray' (0x1f2ce3620) [/System/Library/Frameworks/CoreFoundation.framework]"
)}'. This will be disallowed in the future.`

**Comment by enginseer-dev** [comment]
Hello @vitalii-noname, thank you for bringing this issue to our attention. We've noted your report and added it to our backlog. Appreciate your cooperation!

**Comment by enginseer-dev** [comment]
Hello @vitalii-noname, the issue has been fixed in the latest release of the iOS SDK:
https://github.com/Pushwoosh/pushwoosh-ios-sdk/releases/tag/6.5.3
Please upgrade you Pushwoosh plugin to the latest version.
