### ISSUE TITLE
[Bug]: App Size increasing after receiving Rich Notification 

### ISSUE THREAD

**Issue by ishteyaque06** [Pushwoosh/pushwoosh-ios-sdk#116]
### Documentation

- [X] I've checked the guide, but it doesn't help me to resolve the issue.

### Description

After receiving attachment(images, video) in notification payload App Document&Data size getting increased. In some phone it is upto 6GB.
I have added NotificationService Extension as suggested in example

### Bug severity

High

### Steps to Reproduce

Sent Rich Notification with Video
Check app size in setting
Document and Data Size increased

### Your Pushwoosh iOS SDK version

6.4.8

### Affected iOS versions

iOS16 and above

**Comment by ishteyaque06** [comment]
Some how OS is not deleting NSTemporaryDirectory after copying into UNNotificationAttachment . I have delete path Using 
if FileManager.default.fileExists(atPath: temDirectory.path) {
                    try FileManager.default.removeItem(at: temDirectory)
               }

**Comment by akidisdev** [comment]
@ishteyaque06 Hi! Could you please provide the complete code for the Service Notification Extension? We would like to review it.

**Comment by ishteyaque06** [comment]
class NotificationService: UNNotificationServiceExtension {

    var contentHandler: ((UNNotificationContent) -> Void)?
    var bestAttemptContent: UNMutableNotificationContent?

    override func didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
        self.contentHandler = contentHandler
        bestAttemptContent = (request.content.mutableCopy() as? UNMutableNotificationContent)

		guard let bestAttemptContent = bestAttemptContent else {
			return
		}
		guard let attachmentUrlString = request.content.userInfo["attachment"] as? String else {
			return
		}
		guard let url = URL(string: attachmentUrlString) else {
			return
		}
		
		URLSession.shared.downloadTask(with: url, completionHandler: { (optLocation: URL?, optResponse: URLResponse?, error: Error?) -> Void in
			if error != nil {
				print("Download file error: \(String(describing: error))")
				return
			}
			guard let location = optLocation else {
				return
			}
			guard let response = optResponse else {
				return
			}
			
			do {
				let lastPathComponent = response.url?.lastPathComponent ?? ""
				var attachmentID = UUID.init().uuidString + lastPathComponent
				
				if response.suggestedFilename != nil {
					attachmentID = UUID.init().uuidString + response.suggestedFilename!
				}
				
				let tempDict = NSTemporaryDirectory()
				let tempFilePath = tempDict + attachmentID
				
				try FileManager.default.moveItem(atPath: location.path, toPath: tempFilePath)
                                 let temDirectory = URL.init(fileURLWithPath: tempFilePath)
				let attachment = try UNNotificationAttachment.init(identifier: attachmentID, url: URL.init(fileURLWithPath: tempFilePath))
				
				bestAttemptContent.attachments.append(attachment)
                               //Changes Made Here
                              if FileManager.default.fileExists(atPath: temDirectory.path) {
                                      try FileManager.default.removeItem(at: temDirectory)
                                }

			}
			catch {
				print("Download file error: \(String(describing: error))")
			}
			
			OperationQueue.main.addOperation({() -> Void in
				self.contentHandler?(bestAttemptContent);
			})
		}).resume()
    }
    
    override func serviceExtensionTimeWillExpire() {
        // Called just before the extension will be terminated by the system.
        // Use this as an opportunity to deliver your "best attempt" at modified content, otherwise the original push payload will be used.
        if let contentHandler = contentHandler, let bestAttemptContent =  bestAttemptContent {
            contentHandler(bestAttemptContent)
        }
    }

}

**Comment by enginseer-dev** [comment]
@ishteyaque06 hi there,

Thank you for sharing the complete code for your Notification Service Extension. We'll analyze it thoroughly and consider adding it to our backlog for future enhancements. Your detailed explanation and cooperation are highly appreciated.

We may also include this in our documentation to assist others facing similar issues. Please don't hesitate to reach out to us again if you need further assistance or have more insights to share.
