### ISSUE TITLE
[Question]: Please add tag for v6.7.0

### ISSUE THREAD

**Issue by aidan-24com** [Pushwoosh/pushwoosh-ios-sdk#118]
### Documentation

- [X] I've checked the guide, but I didn't find the information I needed there.

### Question

We are unable to complete `pod install` with latest version as the git commands cannot find the tag `6.7.0`

**Comment by akidisdev** [comment]
Hey @aidan-24com,

Just a heads-up—version 6.7.0 has some critical issues, so we’ve removed it for now. Please switch to version 6.6.1, which should work without any problems. Let us know if you run into any issues with that version!

Thanks for your understanding!
