### ISSUE TITLE
Debug symbols are missing when using SPM

### ISSUE THREAD

**Issue by horsejockey** [Pushwoosh/pushwoosh-ios-sdk#121]
<img width="731" alt="Screenshot 2024-10-01 at 9 10 07 PM" src="https://github.com/user-attachments/assets/64a2c28a-0480-4521-a74c-93605ebbb4c3">

**Comment by enginseer-dev** [comment]
Hello, @horsejockey 

These warnings related to missing dSYM files are not specific to the Pushwoosh framework but are being experienced across multiple frameworks, including AdMob and Google UMP, when using Xcode 16. Based on community feedback and other related issues (e.g., [Sentry Cocoa GitHub issue](https://github.com/getsentry/sentry-cocoa/issues/4068) and [Apple Developer Forum thread](https://developer.apple.com/forums/thread/761589)).

It seems to be an issue with Xcode 16.

If the warnings are disruptive to your workflow and you'd prefer to avoid them, an alternative option is to roll back to Xcode 15, where these warnings were not present. Xcode 15 should allow you to build your app without these issues until Apple provides a resolution in a future Xcode 16 update.

We are also tracking this issue and will provide an update as more information becomes available.

**Comment by horsejockey** [comment]
Thank you. It is not an issue for me. It seems though that if I got a crash inside the Pushwoosh framework I would not be able to provide good information to your team about where it was happening if the dsyms are missing. So I guess is this warning accurate in that sense?
