### ISSUE TITLE
[Question]:  Please migrate to the non-deprecated UIApplication.open(_:options:completionHandler:)

### ISSUE THREAD

**Issue by lilyghukasyan** [Pushwoosh/pushwoosh-ios-sdk#123]
### Documentation

- [X] I've checked the guide, but I didn't find the information I needed there.

### Question

Hi,

In version 6.7.9 (the latest version, currently) the issue is still present. I can see the following message when tapping an action button from In-App banner screen, with deeplink setup:

BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).

I've noticed at least one place, where the deprecated method is still used:
<img width="848" alt="Screenshot 2024-11-26 at 19 25 06" src="https://github.com/user-attachments/assets/31bf91bf-6128-48a8-b77a-6e019ff9759f">

Probably the change in version 6.7.7 didn't include all usages of the deprecated method. 
Could you please fix?

Thank you

**Comment by enginseer-dev** [comment]
Hello, @lilyghukasyan 

Thank you for bringing this to our attention.

We will migrate the rest of the deprecated openURL methods in the next release on the iOS SDK.

**Comment by enginseer-dev** [comment]
Hello, @lilyghukasyan 

The depreciated method was replaced in the latest release of the iOS plugin:
https://github.com/Pushwoosh/pushwoosh-ios-sdk/releases/tag/6.7.11

Thank you for bringing the issue to our attention!
