### ISSUE TITLE
didRegisterForRemoteNotificationsWithDeviceToken loops infinitely

### ISSUE THREAD

**Issue by tschubotz** [Pushwoosh/pushwoosh-ios-sdk#14]
I integrated Pushwoosh into my app like described here: https://www.pushwoosh.com/programming-push-notification/ios/native-ios-sdk-integration/ 

After calling ```[[PushNotificationManager pushManager] registerForPushNotifications]```, the callback ```application: didRegisterForRemoteNotificationsWithDeviceToken:``` in my AppDelegate is called infinitely.

In the debug output I see the following, repeated over and over:
```Sending request: {"request":...```
```To urL https://cp.pushwoosh.com/json/1.3/registerDevice is accessed ```
```Response "200 no error": string: {"status_code":200,"status_message":"OK","response":{"iosCategories":[]}}```
```Registered for push notifications: d...```

In the end, the device is not registered with Pushwoosh, but ```application: didRegisterForRemoteNotificationsWithDeviceToken:``` keeps looping.

If I remove ```[[PushNotificationManager pushManager] handlePushRegistration:deviceToken]``` from ```application: didRegisterForRemoteNotificationsWithDeviceToken:``` then there is no infinite loop, so I suspect it originates from there.

Any ideas?

**Comment by Enriquecm** [comment]
Thanks for the reply, I had the same issue and it was solved by removing these lines:
```
  - (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings;
    {
        [[UIApplication sharedApplication] registerForRemoteNotifications];
    }
```

**Comment by shaders** [comment]
Right. That fixes the problem. At this time SDK prevents multiple registrations calls within short period of time. Effectively fixing the issue as well.
