### ISSUE TITLE
Push notifications aren't sent

### ISSUE THREAD

**Issue by mounibec** [Pushwoosh/pushwoosh-ios-sdk#15]
Notifications aren't sent to the device, while the server API response says otherwise. Here is the log: 

 => #<HTTParty::Response:0x7fc8137d1c60 parsed_response={"status_code"=>200, "status_message"=>"OK", "response"=>{"Messages"=>["CODE_NOT_AVAILABLE"]}}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"server"=>["nginx/1.4.2"], "date"=>["Wed, 28 Jan 2015 16:25:38 GMT"], "content-type"=>["application/json; charset=utf8"], "transfer-encoding"=>["chunked"], "connection"=>["close"], "x-powered-by"=>["phpDaemon/1.0-beta3"], "access-control-allow-origin"=>["*"], "access-control-allow-headers"=>["Origin, X-Requested-With, Content-Type, Accept"], "access-control-allow-methods"=>["GET, POST, PUT, OPTIONS"], "x-pw-cluster-node"=>["api-04"], "x-pw-front-node"=>["front-03"]}>

**Comment by shaders** [comment]
Check the "push status" page to get more insights on what could go wrong. Please note you will not get message code is the message is about to be sent immediately and the devices count are less than 10.
