### ISSUE TITLE
Certificate push configuration error

### ISSUE THREAD

**Issue by nicolasgoutaland** [Pushwoosh/pushwoosh-ios-sdk#16]
Hi,
I am using pushwoosh in several applications and it works great.
Currently, I have a multi target applications using push.
For specific needs, some target do not needs push, and others need it.
The problem is that Pushwoosh will display an error message at launch if the certificate is invalid, even if I am not registering for push.
The only work around I found is to unlink framework from targets not needing it.
Is there any way to configure this behavior, preventing the warning to be displayed ?
Regards

**Comment by shaders** [comment]
Would special setting to prevent this alert in Info.plist would work for you?

**Comment by nicolasgoutaland** [comment]
Hi,

this can be useful. But I think that adding a property or a method to check by code that certificate is valid or not can be useful too.

**Comment by shaders** [comment]
Now the SDK will display the alert only after registration for pushes has been called. The update has been pushed live.

**Comment by sansuba** [comment]
Hi,
What is the reason for the error of "duplicate symbol _llvm.cmdline in..... " and finally 

ld: 120 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

if some one know the issue, please reply soon.
