### ISSUE TITLE
settags function cause the application to crash

### ISSUE THREAD

**Issue by mohamedghonemi** [Pushwoosh/pushwoosh-ios-sdk#18]
when calling 
        [[PushNotificationManager pushManager] setTags:tags];

I get this exception

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]'

**Comment by DimanAM** [comment]
Fixed in 3.0.0 release
