### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by sansuba** [Pushwoosh/pushwoosh-ios-sdk#24]
Hi,
What is the reason for the error of "duplicate symbol _llvm.cmdline in..... " and finally 

ld: 120 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

My xcode version is 6.4

if some one know the issue, please reply soon.

**Comment by shaders** [comment]
I suspect the new bitcode requirements confuses XCode 6.4
You need to upgrade XCode to 7.0 (or 7.0.1).
