### ISSUE TITLE
App crash on iOS 8.3 with Pushwoosh iOS SDK 3.0.11  dynamicDidRegisterUserNotificationSettings

### ISSUE THREAD

**Issue by PlayDevelop** [Pushwoosh/pushwoosh-ios-sdk#25]
The issue was found in 3.0.11 
Same issue found in 3.0.10 

Roll back to 3.0.9  the issue is gone.  

Incident Identifier: 12E6EF25-754D-40AB-8501-9BFB738295A6
CrashReporter Key:   7600a8dc976e25751f95cad9da1e0a58b2e2484a
Hardware Model:      iPhone7,2
Process:             MP Beta [229]
Path:                /private/var/mobile/Containers/Bundle/Application/3484FA6D-4B13-4CD7-A6BB-7146FDD56F31/MP Beta.app/MP Beta
Identifier:          com.avinode.MarketplaceBeta
Version:             174 (1.2.4.4)
Code Type:           ARM-64 (Native)
Parent Process:      launchd [1]

Date/Time:           2015-11-04 11:22:52.112 +0100
Launch Time:         2015-11-04 11:22:51.105 +0100
OS Version:          iOS 8.3 (12F70)
Report Version:      105

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_PROTECTION_FAILURE at 0x000000016fc57fe0
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_platform.dylib      	0x0000000197791500 __bzero + 0
1   libsystem_malloc.dylib        	0x000000019773a82c _nano_malloc_check_clear + 1096
2   libsystem_malloc.dylib        	0x00000001977390d8 nano_calloc + 76
3   libsystem_malloc.dylib        	0x000000019772d958 malloc_zone_calloc + 120
4   libsystem_malloc.dylib        	0x000000019772d8b8 calloc + 60
5   libdispatch.dylib             	0x00000001975d8a90 _dispatch_continuation_alloc_from_heap + 64
6   libdispatch.dylib             	0x00000001975c78c4 _dispatch_barrier_async_f_slow + 40
7   MP Beta                       	0x000000010026a160 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:233)
8   MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
9   MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
10  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
11  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
12  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
13  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
14  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
15  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
16  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
17  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
18  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
19  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
20  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
21  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
22  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
23  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
24  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
25  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
26  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
27  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
28  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
29  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
30  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
31  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
32  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
33  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
34  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
35  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)
36  MP Beta                       	0x000000010026a194 dynamicDidRegisterUserNotificationSettings (PushRuntime.m:239)

**Comment by shaders** [comment]
Bug confirmed, fix will be published today.

**Comment by PlayDevelop** [comment]
Good job team! Thanks a lot

**Comment by mknippen** [comment]
I'm still having this crash with version 4.2.1 of the libs. Has anyone else seen this?

**Comment by DimanAM** [comment]
@mknippen 
This might happen in some rare circumstances.
Should be fixed in 4.2.2.

**Comment by mknippen** [comment]
Great, thank you. I will update and confirm.
