### ISSUE TITLE
Pushwoosh_DEBUG not working with Cocoapods

### ISSUE THREAD

**Issue by xdoug7** [Pushwoosh/pushwoosh-ios-sdk#26]
Hello,
I used to use the Pushwoosh framework directly in my project but not I'm migrating all third-party libraries to Cocoapods and when I did this the flag `Pushwoosh_DEBUG` stopped working.

```
<key>Pushwoosh_DEBUG</key>
<false/>
```

**Comment by DimanAM** [comment]
Pushwoosh_DEBUG was replaced with Pushwoosh_LOG_LEVEL since 3.0.5 version. See https://github.com/Pushwoosh/pushwoosh-ios-sdk/blob/master/Documentation/InfoPlist.md for more information about Pushwoosh properties.
