### ISSUE TITLE
over 200 warnings when building my app with the dSYM information

### ISSUE THREAD

**Issue by sgoodwin** [Pushwoosh/pushwoosh-ios-sdk#27]
Everywhere I have seen recommends simply disabling dSYM information in build settings.

Changing to only building with DWARF information is not a valid solution as that prevents me from symbolicating crash logs from my app later. We need a real solution for this.

**Comment by shaders** [comment]
Take a look here:
https://forums.developer.apple.com/thread/17921

You can try disabling CLANG_ENABLE_MODULES.

**Comment by sgoodwin** [comment]
I've tried that and it didn't make a difference. Please don't close this issue as it is not solved.

**Comment by shaders** [comment]
I'll reopen this, but I'm not sure how to fix this since that's what Apple has changed....

**Comment by fanruten** [comment]
I also have this problem.

It's problem of Pooshwoosh framework. And CLANG_ENABLE_MODULES should be disabled in framework.

Please read https://forums.developer.apple.com/thread/17921 and fix it issue.

**Comment by DimanAM** [comment]
It is not a solution. It's a dirty workaround that destroys all the benefits of using modules.

**Comment by shaders** [comment]
I'm closing this thread. This should be resolved by Apple.

**Comment by aalittle** [comment]
Any specific reason why Apple's suggestion can't be followed? 
> Note that once you disabled module debugging (CLANG_ENABLE_MODULES = NO) turning on clang > modules or precompiled headers should work fine for static libraries. If it doesn't, please file a bug 
> report so we can investiagte what's going on there."

**Comment by shaders** [comment]
Because in this case you'll have to add frameworks manually to your project.
This will end up with gazilion of support tickets when people fail to link correct frameworks to the project.

**Comment by shaders** [comment]
This has been fixed in Pushwoosh SDK version 3.1.1
