### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by niranjanbprajapati** [Pushwoosh/pushwoosh-ios-sdk#29]
I am getting  following error while running application on device.

dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /var/mobile/Containers/Bundle/Application/957B5CD6-7205-4C18-891B-9B11BA3FC717/theofficeshop.app/theofficeshop
  Reason: image not found

**Comment by shaders** [comment]
Take a look here:
http://stackoverflow.com/questions/26024100/dyld-library-not-loaded-rpath-libswiftcore-dylib
