### ISSUE TITLE
[PWRequestManager myThreadMainMethod] Crash.

### ISSUE THREAD

**Issue by majidtbox** [Pushwoosh/pushwoosh-ios-sdk#30]
I have integrated Pushwoosh SDK in iOS app. Fabric is reporting a crash related to pushwoosh in App. Here is full stack trace for crash: 

PWRequestManager.m line 68
-[PWRequestManager myThreadMainMethod]
Crashed: Thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000028

Crashed: Thread
0  CoreFoundation                 0x18199228c _CFStringCreateWithFormatAndArgumentsAux2
1  CoreFoundation                 0x1818bd45c CFStringCreateWithFormat
2  CoreFoundation                 0x1819d12cc __CFAllocateObject2
3  CoreFoundation                 0x1818b2c5c +[__NSArrayM __new:::::]
4  CoreFoundation                 0x1818b29c0 +[NSArray array]
5  MagZine                        0x1001c030c -[PWRequestManager myThreadMainMethod](PWRequestManager.m:68)
6  Foundation                     0x18238bc40 __NSThread__start__
7  libsystem_pthread.dylib        0x181633b28 _pthread_body
8  libsystem_pthread.dylib        0x181633a8c _pthread_body
9  libsystem_pthread.dylib        0x181631028 thread_start

**Comment by shaders** [comment]
Thanks! The team is on it!
