### ISSUE TITLE
Push permissions asking prompt

### ISSUE THREAD

**Issue by Tokanod** [Pushwoosh/pushwoosh-ios-sdk#31]
Hi,

We integrated pushwoosh SDK in our app and are asking the permissions after some specific actions in the app only. When those actions are validated, then we are calling ```registerForPushNotifications``` from the ```PushNotificationManager```. No other part in the code is prompting the permissions.

However, sometimes and very rarely (we haven't been able to pin point a scenario yet), the push prompt is presented at launch, without going through the actions I mentioned just before.
For info, we have those 3 methods that are called from the ```PushNotificationManager``` when the permissions are not accepted yet.
```
setTags
handlePushReceived
sendAppOpen
```

We are using the version 3.1.2 of the SDK. Is it possible that some similar issue has been fixed since then?

Thank you.

Best regards

**Comment by shaders** [comment]
I would recommend to update to 4.0.7. Which is the current version of the SDK.

Do you use any other plugins that may call iOS functions to register for push notifications?

The SDK does not call register for push notifications automatically.

**Comment by Tokanod** [comment]
Hi,

Thank you for your answer.

We were able to debug what was going on. 

To protect against unnecessary call to `registerForPushNotifications` on startup to get a new token if needed, we are checking the following:
`[application isRegisteredForRemoteNotifications]` and this returns **YES**, even though the application is not in present in the notification center.

However, calling `[application currentUserNotificationSettings]` returns **UIUserNotificationTypeNone**.

It looks like the device sometimes presents an inconsistent state since the app is coming from a fresh install...

Thanks for your answer.

**Comment by shaders** [comment]
Thanks. That's a great insights!
