### ISSUE TITLE
Cocoa pods integration for swift

### ISSUE THREAD

**Issue by beribas** [Pushwoosh/pushwoosh-ios-sdk#32]
Hi,

are there plans to support integration through cocoapods for swift projects? As far as I understand, the documentation says one should manually integrate the PushWoosh-framework for swift. The cocoapods integration works only for ObjC?

Thanks

**Comment by shaders** [comment]
Hi,

It should be really simple. Have you tried this article?
http://stackoverflow.com/questions/31884507/how-to-use-objective-c-cocoapods-in-a-swift-project

**Comment by beribas** [comment]
Hi, 

I tried to use it as a dynamic framework but the `import Pushwoosh` doesn't work, "can't find module". However, now I tried to use it without `use_frameworks!` flag in combination with bridging header. It works. Would be great if you can update the documentation. 

Thanks

**Comment by donnywals** [comment]
I'm having this same issue.. Not using `use_frameworks!` isn't an option for me since Pushwoosh is just one of a bunch of dependencies I have in my app and all work perfectly fine except for Pushwoosh. Do I really need to manually drag the Pushwoosh framework in?

**Comment by DimanAM** [comment]
Pushwoosh integration for Swift used to require manual implementation of Objective-C bridging header. Since 5.0.0 Pushwoosh is a modular framefork and can be simply imported using `import Pushwoosh`.
