### ISSUE TITLE
Disable banner notification when app is in background

### ISSUE THREAD

**Issue by Sukaneshbr** [Pushwoosh/pushwoosh-ios-sdk#35]
I want to disable the notification that pushwoosh sdk is building and shoot my own custom notification. I have tried both Pushwoosh_ALERT_TYPE and Pushwoosh_SHOW_ALERT as per documentation, both works fine when the app is in foreground, but i need to customise when the app is in background.

Thanks in advance

**Comment by DimanAM** [comment]
When the app is in background all notifications are handled and displayed by iOS. It is impossible to change notification style in background programmatically. http://stackoverflow.com/questions/11412894/change-style-of-apple-push-notification-programmatically
