### ISSUE TITLE
UIApplication Category?

### ISSUE THREAD

**Issue by tiagoalmeida** [Pushwoosh/pushwoosh-ios-sdk#36]
Even though I am not using any PushWoosh calls (for now) I get this log:

`2016-07-26 12:05:48.393 Lidl[16322:507039] [PW] [I] +[UIApplication(Pushwoosh)] Pushwoosh: Initializing application runtime`

I have no idea what you guys are doing, but using categories to override behaviour seems extremely dangerous to me. What are you doing over there?

**Comment by shaders** [comment]
We are overriding the following property:  
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/#//apple_ref/occ/instp/UIApplication/applicationIconBadgeNumber

So auto incrementing badges will work. This code has been tested gazillion times, it's safe.

**Comment by RuiAAPeres** [comment]
<img width="752" alt="screen shot 2016-08-09 at 17 48 43" src="https://cloud.githubusercontent.com/assets/949286/17525186/8d17bbb4-5e59-11e6-8e09-513b165f5fbf.png">

**Comment by shaders** [comment]
Yes we are very careful with names and everything. You might remove -ObjC -all_load linker flags, this way categories from library would not be loaded. Though you would lose autobadges func.

**Comment by tiagoalmeida** [comment]
Is there any other way to remove this "feature" without messing around with linker flags? As far as I saw we can only remove this removing the push woosh entirely.
