### ISSUE TITLE
Long time for setTags to take effect.

### ISSUE THREAD

**Issue by Andre-FS** [Pushwoosh/pushwoosh-ios-sdk#37]
While yesterday calling `loadTags` right after `setTags` would return the correct result, today I'm having up to 10 minutes delay before I see changes in `loadTags` or the [browser dashboard](https://cp.pushwoosh.com/v2/tags). 

Is this expected behaviour?

**Comment by shaders** [comment]
On a rare situation when there are queues in the system this might happen. Though as I mentioned this is rare situation and this is monitored by our team.

**Comment by Andre-FS** [comment]
Ok, thank you for your answer.

Is this something that should also affect other SDK requests? 
For instance, today I'm seeing `loadTags` request taking a long time to complete in very good network connections, and some other requests returning ` Status:   "504 gateway timed out"`. 

This is while using a Marketing account.

How unusual is it for service outages to occur?
Also, is there anywhere where I can check the overall service status?

**Comment by shaders** [comment]
Yesterday we've had a major outage after DDos attack. We are investigating the case and we'll report this by email later.
