### ISSUE TITLE
iOS10 Support

### ISSUE THREAD

**Issue by yanamura3** [Pushwoosh/pushwoosh-ios-sdk#40]
UIUserNotificationSettings is deprecated since iOS10.
<s>It seems Pushwoosh does not work on iOS10 because "application:didRegisterForRemoteNotificationsWithDeviceToken" never called.</s>

Do you have any plan to support iOS10?

**Comment by shaders** [comment]
Did you add aps-environment entitlements?
Current Pushwoosh SDK supports iOS10. The update will be released next week that will bring all the additional iOS10 features support.
