### ISSUE TITLE
Integration using the cordova plugin?

### ISSUE THREAD

**Issue by javacado** [Pushwoosh/pushwoosh-ios-sdk#42]
Just to clarify, if I am using the pushwoosh cordova plugin, do I only need to replace the Pushwoosh.framework directory (located in plugins/pushwoosh-cordova-plugin/src/ios/) with the Pushwoosh.framework directory located in this repo?

OR should I update the cordova plugin? (have you integrated this latest ios 10 compatible sdk into the cordova plugin?)

Thanks

**Comment by shaders** [comment]
Just updating the plugin should be fine. The latest Cordova plugin version already includes 4.1.2 iOS SDK.
