### ISSUE TITLE
Unable to Install Latest Version 4.1.2

### ISSUE THREAD

**Issue by mahesh-agrawal** [Pushwoosh/pushwoosh-ios-sdk#43]
I am trying to install the version 4.1.2 which is the latest stable version for iOS 10. as per the mail i received. But when am installing through cocoa pod its not getting installed. Its only installing 4.1.0. But on the website of cocoa pod its shown that 4.1.2 is the latest version. Below my terminal log screenshot. http://screencast.com/t/CuSh8fFSeMQb

**Comment by ARFAOUI** [comment]
force it using 
pod 'Pushwoosh', '~> 4.1.2'
in your Podfile

**Comment by mahesh-agrawal** [comment]
tried but no luck. see here.. http://screencast.com/t/NGF1hKqRxw

**Comment by DimanAM** [comment]
@mahesh-agrawal 
Try updating source repos as mentioned in log:
```shell
 pod repo update
```

**Comment by mahesh-agrawal** [comment]
same response as above. kind of stuck...tried lots of option. i think there is something wrong with the cocoa pod uploaded by Pushwoosh.

**Comment by shaders** [comment]
It is 4.1.2 uploaded to Cocoapods:
https://github.com/CocoaPods/Specs/blob/master/Specs/Pushwoosh/4.1.2/Pushwoosh.podspec.json
https://cocoapods.org/pods/Pushwoosh

I see from the screenshots your cocoapods are asking to do "pod repo update" command.
Can you send a screenshot with the results of this command?

**Comment by mahesh-agrawal** [comment]
here is the screenshot when i tried to update. http://screencast.com/t/4tAhIsqX

**Comment by shaders** [comment]
It says you cannot run Cocoapods as root. That's why it doesn't update anything. Try to remove sudo command? Or somehow not to start cocoapods as root?

**Comment by mahesh-agrawal** [comment]
I tried to remove sudo command and the same result. can you please tell me how i can start without cocoapods as root? bit confused.

**Comment by shaders** [comment]
That's strange if you see the same error when removing "sudo".

Maybe this article could help:  
http://stackoverflow.com/questions/23190064/cant-run-sudo-pod-install-after-updating-to-cocoapods-0-32-1-with-error-you-ca  
https://github.com/CocoaPods/CocoaPods/issues/2070

I'm sorry I can't tell that much about CocoaPods behavior :( Maybe asking CocoaPods guys will help better.
