### ISSUE TITLE
Crash on iOS 7

### ISSUE THREAD

**Issue by bamx23** [Pushwoosh/pushwoosh-ios-sdk#46]
There is a crash on iOS 7 in `[PushNotificationManager pushManager]`:
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString containsString:]: unrecognized selector sent to instance 0x170034040'
```
The method `- [NSString containsString]` is available only from iOS 8.

**Comment by shaders** [comment]
Duplicate https://github.com/Pushwoosh/pushwoosh-ios-sdk/issues/45
