### ISSUE TITLE
If the image url without extension on iOS 10 Rich Notifications Integration it doesn't show

### ISSUE THREAD

**Issue by iTarek** [Pushwoosh/pushwoosh-ios-sdk#47]
Hello
iOS 10 Rich Notifications Integration is working good, but we have one issue
If the image url without extension it doesn't show

This is example...

{
	"aps": {
		"mutable-content": 1
	},
	"attachment": "http://www.aljazeera.net/file/GetImageCustom/a7e13576-80da-441a-8250-1281e1d95201/1200/630"
}

**Comment by shaders** [comment]
Nice spotted! Updated Service Extension has been published!

https://github.com/Pushwoosh/pushwoosh-ios-sdk/blob/master/Samples/iPhone/NotificationService/NotificationService.m

**Comment by shaders** [comment]
close via https://github.com/Pushwoosh/pushwoosh-ios-sdk/commit/ee23238ee06f5326a72d1db0692be19a65140c89
