### ISSUE TITLE
Random crash in version 4.1.3

### ISSUE THREAD

**Issue by Axort** [Pushwoosh/pushwoosh-ios-sdk#49]
Hi!

Since the release of iOS 10 we've been experiencing some random crashes throughout our app related to Pushwoosh SDK.

We have integrated the SDK via Cocoapods and we have the latest version: 4.1.3 (as of the creation of this issue). We're testing on an iPhone 6 Plus with iOS 9.3.5 and sometimes a crash occurs. We don't have the steps to reproduce it since it happens randomly in different view controllers and different situations.

Here is an image displaying the crash in Xcode 8:

<img width="1440" alt="captura de pantalla 2016-10-05 a la s 12 05 15" src="https://cloud.githubusercontent.com/assets/4009741/19123388/162cdf8a-8af4-11e6-873b-6cf49cd796fb.png">

Thanks.

**Comment by verixverck** [comment]
Same problem here :(

**Comment by DimanAM** [comment]
Should be fixed in 4.1.4. Please try updated version.

**Comment by Axort** [comment]
Great! I've updated it and it appears to be fixed; we'll keep testing the app.
Thanks.

**Comment by shaders** [comment]
👍
