### ISSUE TITLE
Few images doesn't load on iOS 10 Rich Notifications, Why?

### ISSUE THREAD

**Issue by iTarek** [Pushwoosh/pushwoosh-ios-sdk#50]
Can you please explain why image like this one does not show on iOS 10 Rich Notifications, while the image url is correct!

{"aps":{"mutable-content":1},"attachment":"http:\/\/iphoneislam.com\/wp-content\/uploads\/2016\/10\/Zamen_iOS10_1-590x332.jpg"}

**Comment by shaders** [comment]
I see this is HTTP URL. Did you follow this step in the guide:
http://docs.pushwoosh.com/docs/ios-10-rich-notifications-integration#3-allowing-non-secure-attachment-urls

**Comment by iTarek** [comment]
Yes Sure
You can try this
{"aps":{"mutable-content":1},"attachment":"http:\/\/iphoneislam.com\/wp-content\/uploads\/2016\/10\/Zamen_iOS10_1-590x332.jpg"}
if it worked with you and it show image on the push, close the issue, if not just tell me the reason.

**Comment by shaders** [comment]
It showed the image perfectly... Make sure you add HTTP URL handling as per guide above. This is very important.

**Comment by Matsepura** [comment]
Had the same issue. In my case, I forgot add this one:

**Comment by anirudhsmarttechnica** [comment]
{  "notification": {
    "body" : "This week’s edition is now available.",
    "title": "Portugal vs. Denmark",
    "text": "5 to 1",
    "content_available": 1
  },
  "data" : {
    "volume" : "3.21.15",
    "contents" : "http://www.smarttechnica.com/project/ss/images/category/thumb/79941489597927.jpg"
  },
  "to" : "fFAbfpB55QA:..........", 
  "priority" : "high"
}

Same here..Image not come..

**Comment by ankit0812** [comment]
{
 “to”: “TO_BE_SENT_TOKEN”,
 “content_available”: true,
 “mutable_content”: true,
 “priority”: “high”,
 “notification”: {
     “title”: “Custom title”,
     “subtitle”: “Custom subtitle”,
     “body”: “Custom body”,
     “sound”: “store_notif.mp3”,
     “badge”: 1
 },
 “data”: {
     “type”: “notificationType”,
     “attachment-url”: “https://www.cleverfiles.com/howto/wp-content/uploads/2018/03/minion.jpg”
 }
}

Works perfectly check this
