### ISSUE TITLE
Pushwoosh_ALERT_TYPE Banner does not look like iOS 10 UI

### ISSUE THREAD

**Issue by iTarek** [Pushwoosh/pushwoosh-ios-sdk#51]
On iOS 10 when app is running in the foreground the Pushwoosh Banner looks like iOS 9 UI, you should have iOS 10 Banner with support of iOS 10 rich notification image.

This will be a nice touch.

**Comment by wfhm** [comment]
Hi, 

We have put it in our roadmap, so as soon as there will be any progress we will update this thread.

**Comment by shaders** [comment]
This has been supported in iOS SDK 5.0 

```
 // set default Pushwoosh delegate for iOS10 foreground push handling
    [UNUserNotificationCenter currentNotificationCenter].delegate = [PushNotificationManager pushManager].notificationCenterDelegate;
```

You can find more information here:
http://docs.pushwoosh.com/docs/native-ios-sdk
