### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by geme** [Pushwoosh/pushwoosh-ios-sdk#52]
I would love to see carthage support.
Pushwoosh would be the only dependency in my project which needs cocoapods.
I tried to add just the framework but i get linker error.

`Undefined symbols for architecture armv7:
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in Pushwoosh(libPushNotificationManager.a-armv7-master.o)
  "___gxx_personality_sj0", referenced from:
      -[PWZipArchive dealloc] in Pushwoosh(libPushNotificationManager.a-armv7-master.o)
      -[PWZipArchive createZipFile2:] in Pushwoosh(libPushNotificationManager.a-armv7-master.o)
      -[PWZipArchive createZipFile2:password:] in Pushwoosh(libPushNotificationManager.a-armv7-master.o)
      -[PWZipArchive addFileToZip:newname:] in Pushwoosh(libPushNotificationManager.a-armv7-master.o)
      -[PWZipArchive unzipOpenFile:] in Pushwoosh(libPushNotificationManager.a-armv7-master.o)
      -[PWZipArchive unzipOpenFile:password:] in Pushwoosh(libPushNotificationManager.a-armv7-master.o)
      -[PWZipArchive unzipFileTo:overWrite:] in Pushwoosh(libPushNotificationManager.a-armv7-master.o)
      ...
  "std::terminate()", referenced from:
      ___clang_call_terminate in Pushwoosh(libPushNotificationManager.a-armv7-master.o)
ld: symbol(s) not found for architecture armv7
`

it would be much simpler if it would be addable with carthage:
https://github.com/Carthage/Carthage

carthage tells me the pushwoosh does not have a shared scheme. maybe this is all it takes?

**Comment by shaders** [comment]
You'll need to add libstdc++.dylib (or libstdc++.tbd) as per Step 3.5 here:
http://docs.pushwoosh.com/docs/native-ios-sdk

**Comment by geme** [comment]
thank you, i can build now!

but the issue remains, i would love to see a carthage support

**Comment by shaders** [comment]
I'll put this on the roadmap. Thanks!

**Comment by shaders** [comment]
Carthage is now supported from iOS SDK 5.0
