### ISSUE TITLE
403 error when displaying Rich Media with latest versions of the SDK

### ISSUE THREAD

**Issue by fcamaster** [Pushwoosh/pushwoosh-ios-sdk#53]
Hi, 
Let me explain the situation. 
I had installed the Pushwoosh SDK and it was working well for the Rich Media, which is one of the functionalities we're using.
When I updated the SDK to the latest versions, by clicking on a Rich Media notification the app opens and the new window appears, but its content is "403 Forbidden"

What I've found by investigating a little bit more is that, since the version https://github.com/Pushwoosh/pushwoosh-ios-sdk/releases/tag/4.1.1
when the API was changed, this stopped working, so, if I install the version 4.1.0 it works fine.

Is there something you can fix from your side or it's something we might change in the rich media pages?
Additional Info: I've been trying with different APP-ID with the same result, this is one of them: AF3B1-16006

Thanks in advance.

**Comment by shaders** [comment]
I've got this reproduced. Should be fixed soon, I'll keep you posted.

**Comment by shaders** [comment]
Fixed in https://github.com/Pushwoosh/pushwoosh-ios-sdk/commit/2275fa579d7d7ec8ed36180f4dabd0cdc98ad656
