### ISSUE TITLE
Unregister and re-register won't register the device again

### ISSUE THREAD

**Issue by rborn** [Pushwoosh/pushwoosh-ios-sdk#54]
I opened a ticket on the [Titanium module](https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/issues/33) too, but I think it's a native issue :(

**Comment by wfhm** [comment]
Answered in [the main thread](https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/issues/33).
