### ISSUE TITLE
Carthage now supports binary only frameworks

### ISSUE THREAD

**Issue by ffittschen** [Pushwoosh/pushwoosh-ios-sdk#55]
Hi,
first of all, thanks for the carthage integration, that made a lot of our custom build scripts obsolete, that copy the downloaded framework into the correct directories and archive cached carthage build results etc. 👍🏻 Since today, carthage [officially supports](https://github.com/Carthage/Carthage/pull/1760) binary only frameworks, which looks like a perfect fit for Pushwoosh.

This is no request, I just wanted to let you know, that the option exists 😉

**Comment by DimanAM** [comment]
Hi, thank you for the information. Actually carthage had already supported binary only frameworks. They are distributed using github release attachments (e.g https://github.com/Pushwoosh/pushwoosh-ios-sdk/releases/download/5.0.2/Pushwoosh.framework.zip). The recent carthage release added the ability to host binaries anywhere, which is a great feature. However we do not plan to switch from github releases in the nearest future.
