### ISSUE TITLE
Cocoapods - Could not build Objective-C module 'Pushwoosh'

### ISSUE THREAD

**Issue by patBurger** [Pushwoosh/pushwoosh-ios-sdk#56]
Hi guys, 
i've implemented your SDK via cocoapods in my swift-project, but since pushwoosh-ios-sdk v5.1.0 it's no longer possible to compile it.
Compiler throws following Issue in `Pushwoosh.h`:
`InAppManager.h file not found` 

I saw that you have `PWInAppManager.h` in your Header-Files. Is this possibly a naming problem in `Pushwoosh.h`?

Thanks a lot!

**Comment by DimanAM** [comment]
Fixed in 5.1.2.
