### ISSUE TITLE
Re-instate changelog

### ISSUE THREAD

**Issue by shagedorn** [Pushwoosh/pushwoosh-ios-sdk#57]
I don't know the reason behind 5484790bbe1335aab27ea22288b693de8816eb35, but it seems like a bad move to delete the changelog without any kind of replacement. It's been a major version change, the framework is not open source, and you're not telling us what has changed?

**Comment by shaders** [comment]
The changelog has been moved to github releases, which actually provide much more transparency including SDK versions for that release, than a simple readme file.

https://github.com/Pushwoosh/pushwoosh-ios-sdk/releases

**Comment by shagedorn** [comment]
Thanks for clarifying this.

Although I'm glad the information is available, I disagree that GitHub Releases is the better place for them: We usually update through submodules and don't even open GitHub for it, so we cannot glance at what's changed in the git diffs or the file system directly. I also assume that other people who check out the repo don't come back to GitHub looking for them if they don't find anything in the working copy.

Since GitHub release notes aren't version-controlled, we don't have a copy of them either. If you move to the next hip thing in a year and decide to delete the release notes on GitHub, we'll have a hard time finding out what has changed if we want to debug issues in an app that uses older releases.

You should also mention the release notes somewhere on your website. I tried looking for them on your website directly and via Google but could not find anything.

**Comment by shaders** [comment]
I like the idea of having release notes on the website. Thank you for the suggestion!
I've added this to our docs website!

If it helps Github can supply Atom feed of releases as well:
Ex: https://github.com/Pushwoosh/pushwoosh-ios-sdk/releases.atom
