### ISSUE TITLE
Example of NSnotificationService

### ISSUE THREAD

**Issue by axelin** [Pushwoosh/pushwoosh-ios-sdk#58]
Could you add any example of NSNotificationService?

**Comment by wfhm** [comment]
Hi,

We've discussed a possibility of adding such example, and it won't be added in the nearest future. If you have a specific use case which uses NSNotificationService. please contact our [Support Team](https://www.pushwoosh.com/contact-us) and provide them with as many details as possible.

**Comment by shaders** [comment]
Did you mean UNNotificationServiceExtension?
You can find it here: http://docs.pushwoosh.com/docs/ios-10-rich-notifications-integration

**Comment by axelin** [comment]
shaders, I forgot to specify that has to be a Swift example and not Obj-C, my mistake, and your link is an Obj-C example.

**Comment by DimanAM** [comment]
Here is a Swift example: https://github.com/Pushwoosh/pushwoosh-ios-sdk/blob/master/Samples/iPhone-SWIFT/NotificationService/NotificationService.swift
