### ISSUE TITLE
Dependency "pushwoosh-ios-sdk" has no shared framework schemes

### ISSUE THREAD

**Issue by danho322** [Pushwoosh/pushwoosh-ios-sdk#59]
Trying to add pushwoosh sdk through Carthage. Running 
`carthage update --platform iOS --no-use-binaries`
and getting this error:

Dependency "pushwoosh-ios-sdk" has no shared framework schemes

Am I adding it incorrectly?

**Comment by DimanAM** [comment]
Pushwoosh framework is distributed as prebuilt binary. You cannot update it with `--no-use-binaries`.
