### ISSUE TITLE
didReceiveRemoteNotification is not invoked on iOS 10.2.1

### ISSUE THREAD

**Issue by coolazeem** [Pushwoosh/pushwoosh-ios-sdk#60]
Hello, 

On iOS 10.2.1 (Objective C), I do receive notifications promptly from Pushwoosh, but didReceiveRemoteNotification is never invoked.

I wish to run some custom code within the block but unable to do so as it is never executed (whether the app is in background or foreground).

onPushAccepted works fine though.

**Comment by DimanAM** [comment]
[UNUserNotificationCenterDelegate userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter?language=objc) is invoked instead on iOS10. `UNUserNotificationCenterDelegate` is implemented internally in Pushwoosh.framework and is set using

```objc
[UNUserNotificationCenter currentNotificationCenter].delegate = [PushNotificationManager pushManager].notificationCenterDelegate;
```

If you want to have full control over system callbacks you can use your own `UNUserNotificationCenterDelegate`, but do not forget to propagate both callbacks [1](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter?language=objc), [2](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter?language=objc) to `[PushNotificationManager pushManager].notificationCenterDelegate`.

**Comment by coolazeem** [comment]
Now I implemented 
`- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
`

AND

`-(void)userNotificationCenter:(UNUserNotificationCenter *)center
        didReceiveNotificationResponse:(UNNotificationResponse *)response
            withCompletionHandler:(void (^)())completionHandler {`

but both methods are not invoked? I am sure I must be missing something? The notifications come through fine though

**Comment by DimanAM** [comment]
Did you set your delegate with:
```objc
[UNUserNotificationCenter currentNotificationCenter].delegate = self;
```
instead of:
```objc
[UNUserNotificationCenter currentNotificationCenter].delegate = [PushNotificationManager pushManager].notificationCenterDelegate;
```
?

**Comment by coolazeem** [comment]
I had missed that!

Now the below works perfectly fine
`- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler`

However,
`-(void)userNotificationCenter:(UNUserNotificationCenter *)center
        didReceiveNotificationResponse:(UNNotificationResponse *)response
            withCompletionHandler:(void (^)())completionHandler`

is called only when the user taps on the notification. Is there any way this can be invoked if the app is in background (or will that only work if content-available key is equal to 1)?

**Comment by DimanAM** [comment]
> Is there any way this can be invoked if the app is in background (or will that only work if content-available key is equal to 1)?

In this case [application:didReceiveRemoteNotification:fetchCompletionHandler:](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application?language=objc) will be called. You should also enable `Remote notification` in `Background Modes` capability options to achieve that. Please note that it will only work in background (it will not work for killed application) for notifications with `content-available` key.

**Comment by coolazeem** [comment]
Thanks! That was of great help!

**Comment by ashok1089** [comment]
Hi,

userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: needs to be called when a user performs any actions on the notification as per the documentation, But never got called.

I did made my appdelegate as nsnotification center's delegate and turn on the backgound modes.
Really appreciate any help.

**Comment by nsuryanarayanareddyn** [comment]
any update on this

**Comment by ashok1089** [comment]
Could not find any answer. Please let me know if you find any.

Thanks.
