### ISSUE TITLE
Recent Github releases are missing Pushwoosh.framework.zip

### ISSUE THREAD

**Issue by mpaulsonco** [Pushwoosh/pushwoosh-ios-sdk#61]
Releases `5.3.1` and `5.3.2` on Github are missing `Pushwoosh.framework.zip`, breaking support for Carthage.

To reproduce, setup a Cartfile pointing to Pushwoosh and then run `carthage bootstrap --platform iOS`, which will yield: 
```
*** Skipped building pushwoosh-ios-sdk due to the error:
Dependency "pushwoosh-ios-sdk" has no shared framework schemes for any of the platforms: iOS
```

**Comment by wfhm** [comment]
Hi, 

Got it reproduced, will come back with an update shortly.

**Comment by wfhm** [comment]
@mpaulsonco should be fixed now. Could you please try again and let us know about the results?
