### ISSUE TITLE
Application Crash on iOS 11 and Xcode 9.1

### ISSUE THREAD

**Issue by syedqamara** [Pushwoosh/pushwoosh-ios-sdk#66]
> [NSURL isAdtechEvent]: unrecognized selector sent to instance 0x6000000ce460
> 2018-01-09 14:00:52.579203+0500 SFBio[42650:3074432] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSURL isAdtechEvent]: unrecognized selector sent to instance

This crash occurs when below line is executed.
`[PushNotificationManager initializeWithAppCode:@"SomeAppCode" appName:@"Some App Name"];`

Currently i haven't mention my actual keys here due to security reasons. Can you please tell me why this app is crashing.
And if i comment the above line of code and directly start from below line crash still occurs.

`PushNotificationManager *pushManager = [PushNotificationManager pushManager];`

**Comment by wfhm** [comment]
Hi,

It looks not related to Pushwoosh SDK directly. There is no ` isAdtechEvent` method used in our SDK, therefore may I ask you to search for `isAdtechEvent` method calls in your project and double-check that it does not affect Pushwoosh SDK performance?

**Comment by wfhm** [comment]
@syedqamara 

Any news on this one?
