### ISSUE TITLE
Alert Notifications iPhone X

### ISSUE THREAD

**Issue by AlexisMedinaM** [Pushwoosh/pushwoosh-ios-sdk#67]
Hi, I am testing in Iphone X and when I receive a push notification but app is foreground, pushManager shows alert notifications but it doesn't show correctly in iPhone X, others iPhone devices shows the alert notifications correctly. I think that the constraints haven't been update to safe area layouts.

**Comment by wfhm** [comment]
Hi,

Could you please provide us with a bit more details on the issue? Particularly, which Pushwoosh iOS SDK version do you use? By any chance could you please provide us with a screenshot of an incorrectly shown?

**Comment by wfhm** [comment]
@AlexisMedinaM does this issue still persist? Is it possible to provide us with a reproducer?

**Comment by Razuvaev** [comment]
@wfhm I got the same issue, here is the recording: https://www.dropbox.com/s/dz4rohll7azoh0r/IMG_0241.MOV?dl=0

**Comment by wfhm** [comment]
@Razuvaev 

Do you call `PushNotificationManager.push().handlePushReceived(notificationDict)` in your `-(void)application:didReceiveRemoteNotification:fetchCompletionHandler:` method? If so, this method is already called from `UNUserNotificationCenter` delegate. Calling this method twice causes a custom banner to be shown instead of a native one.

Please note you should call this method in didReceiveRemoteNotification only for iOS versions lower​ than 10.

**Comment by Razuvaev** [comment]
@wfhm 
No I don't call PushNotificationManager.push().handlePushReceived(notificationDict) if iOS version is lower than 10 and still got this problem

**Comment by wfhm** [comment]
@Razuvaev 
Could you please show us your `-(void)application:didReceiveRemoteNotification:fetchCompletionHandler:` content?

**Comment by Razuvaev** [comment]
@wfhm 

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
    if SYSTEM_VERSION_LESS_THAN(@"10") {
        [[PushNotificationManager pushManager] handlePushReceived:userInfo];
    }
}

**Comment by wfhm** [comment]
@Razuvaev 

Could you please check that you call the following method in your AppDelegate?

```
[UNUserNotificationCenter currentNotificationCenter].delegate = [PushNotificationManager pushManager].notificationCenterDelegate;
```

**Comment by wfhm** [comment]
@Razuvaev any updates?
