### ISSUE TITLE
"url" disappeared from the APNS payload

### ISSUE THREAD

**Issue by robin7331** [Pushwoosh/pushwoosh-ios-sdk#68]
Hey!

We we're using deeplinks when sending out push notifications.
Somehow we chose to parse those URL's within the ```onPushAccepted``` method in our AppDelegate.

We actually always had a ```url``` JSON key within the ```aps``` root object.
That suddenly disappeared. 

Are we missing something or did you change that?

**Comment by wfhm** [comment]
Hey,

Could you please when exactly did you notice this behavior had changed? Also, did you apply any changes on your application's side?

The URL, if sent as a Pushwoosh deeplink, will be passed as a value of "l" key in a push payload.

**Comment by wfhm** [comment]
@robin7331 Did you manage to solve the issue or is it still persistent?
