### ISSUE TITLE
Singleton method `PushNotificationManager.push()` never returns on iOS 12

### ISSUE THREAD

**Issue by tehpsy** [Pushwoosh/pushwoosh-ios-sdk#71]
On iOS 12.0, if you call `PushNotificationManager.push()` early in the app's lifecycle (e.g. in `application(... didFinishLaunching...)`, then the call never returns and so the main thread hangs. If you instead call this method after a short delay (say 1 second) then the call returns and the app behaves as normal.

**Comment by wfhm** [comment]
Hi,

Checking it.

**Comment by tehpsy** [comment]
Hi @wfhm, did you manage to reproduce the issue?

**Comment by wfhm** [comment]
@tehpsy Hey,

Please accept my strongest apologies for not updating you timely. Investigation of this issue was delayed due to preparing for iOS release, so we had not yet reproduced it. The release is rolled out now, so we can continue, and I will update you as soon as there is any news.

**Comment by tehpsy** [comment]
@wfhm no problem! We've rolled out fixes for our apps that delay the pushwoosh registering by 1 second, so it's not really an issue for us. But it would be nice to remove this delay :) And I expect other users will find this bug too!

**Comment by wfhm** [comment]
Hey @tehpsy ,

Apologies for a delayed response! We were unable to reproduce the issue with iOS 12 beta 6 - our [Swift sample app](https://github.com/Pushwoosh/pushwoosh-ios-sdk/tree/master/Samples/iPhone-SWIFT) works just fine on this OS version.
