### ISSUE TITLE
registerForPushNotifications does not support new iOS 12 UNAuthorizationOptions

### ISSUE THREAD

**Issue by achelsmar** [Pushwoosh/pushwoosh-ios-sdk#73]
Unfortunately there seems to be no way to support new `UNAuthorizationOptions` in iOS 12 such as `providesAppNotificationSettings` or `criticalAlert` with the `registerForPushNotifications()`.

**Comment by wfhm** [comment]
@achelsmar Hey,

We have just rolled out 5.9.0 version of Pushwoosh iOS SDK which introduces support of iOS 12 features.
