### ISSUE TITLE
How get UNNotificationResponse in case of UNUserNotificationCenter.delegate = PushNotificationManager 

### ISSUE THREAD

**Issue by iTarek** [Pushwoosh/pushwoosh-ios-sdk#74]
I want to set...
`[UNUserNotificationCenter currentNotificationCenter].delegate = [PushNotificationManager pushManager].notificationCenterDelegate;`

So I have native banner show when app in the foreground but if I set  ([UNUserNotificationCenter currentNotificationCenter].delegate to PushNotificationManager the method...

```
-(void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler{
    
    //NSLog(@"Userinfo %@",response.notification.request.content.userInfo);
    [self HandleActionsFromNotification:response.notification.request.content.userInfo withIdentifier:response.actionIdentifier];
    
    completionHandler();
}
```

Never fired... and I can not handle user actions buttons because there is no method that get me UNNotificationResponse so I know which button user clicked...

I can fix this problem if I set

`[UNUserNotificationCenter currentNotificationCenter].delegate = self`

But in this case it will not show the Native banner when app in the foreground.

Can you help me please, How to get user response and keep the native banners.

**Comment by wfhm** [comment]
Hi @iTarek ,

1) Call `[UNUserNotificationCenter currentNotificationCenter].delegate = self;`
2) Implement methods of this delegate in your code;
3) For each method call the same method of `[PushNotificationManager pushManager].notificationCenterDelegate;`

Here is a brief example:

```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
    [[PushNotificationManager pushManager].notificationCenterDelegate userNotificationCenter:center willPresentNotification:notification withCompletionHandler:completionHandler];
    // your logics here
}


- (void)userNotificationCenter:(UNUserNotificationCenter *)center 
didReceiveNotificationResponse:(UNNotificationResponse *)response 
         withCompletionHandler:(void (^)())completionHandler {
    [[PushNotificationManager pushManager].notificationCenterDelegate userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
    // your logics here
}
```

Please let us know if it does not work for you.

**Comment by iTarek** [comment]
Thank you for the answer, but still have problem when the app in foreground the function... 

`- (void)userNotificationCenter:(UNUserNotificationCenter *)center 
didReceiveNotificationResponse:(UNNotificationResponse *)response 
         withCompletionHandler:(void (^)())completionHandler {
    [[PushNotificationManager pushManager].notificationCenterDelegate userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
    // your logics here
}`

Do not call, how can I get the actions response when app in foreground?

**Comment by iTarek** [comment]
> Thank you for the answer, but still have problem when the app in foreground the function...
> 
> ```
> - (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler {
> }
> ```
> Do not call, how can I get the actions response when app in foreground?

Hi
Any answer for that point?

**Comment by wfhm** [comment]
@iTarek 

Just checked it - this method is called correctly. Could you please share your complete Pushwoosh implementation code with us so we could have a look?

**Comment by iTarek** [comment]
It's strange it's working on the debug version but not on appstore or testflight version.

This is my pushwoosh implementation 

```
    //-----------PUSHWOOSH PART-----------
    // set custom delegate for push handling, in our case AppDelegate
    PushNotificationManager * pushManager = [PushNotificationManager pushManager];
    pushManager.delegate = self;

    // set default Pushwoosh delegate for iOS10 foreground push handling
    if (@available(iOS 10.0, *)) {
        [UNUserNotificationCenter currentNotificationCenter].delegate = self;
    }
    
    // handling push on app start
    [[PushNotificationManager pushManager] handlePushReceived:launchOptions];
    
    // make sure we count app open in Pushwoosh stats
    [[PushNotificationManager pushManager] sendAppOpen];
    
    // register for push notifications!
    if ([[UIApplication sharedApplication] isRegisteredForRemoteNotifications]) {
        [[PushNotificationManager pushManager] registerForPushNotifications];
    }

//Before iOS 10
- (void)application:(UIApplication *)application handleActionWithIdentifier:(NSString *)identifier forRemoteNotification:(NSDictionary *)notification completionHandler:(void(^)(void))completionHandler {
    [self HandleActionsFromNotification:notification withIdentifier:identifier];
    
    completionHandler();
}

- (void)application:(UIApplication *)application handleActionWithIdentifier:(NSString *)identifier forLocalNotification:(UILocalNotification *)notification completionHandler:(void(^)(void))completionHandler {
    [self HandleActionsFromNotification:notification.userInfo withIdentifier:identifier];
    
    completionHandler();
}

//After iOS 10
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
    
    [[PushNotificationManager pushManager].notificationCenterDelegate userNotificationCenter:center willPresentNotification:notification withCompletionHandler:completionHandler];
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler {
    
    [[PushNotificationManager pushManager].notificationCenterDelegate userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
    
    [self HandleActionsFromNotification:response.notification.request.content.userInfo withIdentifier:response.actionIdentifier];
}
```

**Comment by wfhm** [comment]
@iTarek 

Very strange, there is basically nothing wrong with your code. As a suggestion, please try calling your `HandleActionsFromNotification` method **before** `didReceiveNotificationResponse`, as it has a completion handler and your code might not be executed. 

```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler {
    
    [self HandleActionsFromNotification:response.notification.request.content.userInfo withIdentifier:response.actionIdentifier];

    [[PushNotificationManager pushManager].notificationCenterDelegate userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}
```

If this does not help, most probably, the issue is in your HandleActionsFromNotification method, the rest part of your code is surely correct, and this is the only function we cannot explore.

**Comment by iTarek** [comment]
@wfhm 

After lot of debug now I understand, If the app in the foreground I do not get the userinfo if user click one of the action buttons and always trigger: (null)...
This is how the response if the app in the foreground...

```
Received Push Response: <UNNotificationResponse: 0x2805f56c0; actionIdentifier: 1, notification: <UNNotification: 0x2805f5940; date: 2018-11-15 12:54:30 +0000, request: <UNNotificationRequest: 0x280bfff90; identifier: 2AC73742-646A-4568-8782-B7C46F0715EC, content: <UNNotificationContent: 0x283106340; title: (null), subtitle: (null), body: NEWS BODY, summaryArgument: , summaryArgumentCount: 0, categoryIdentifier: 2075, launchImageName: , threadIdentifier: , attachments: (
    "<UNNotificationAttachment: 0x280bfe280; identifier: B0325954-1922-4D67-961F-B3DE5960D70D206.jpg, family: Image, URL: file:///var/mobile/Library/UserNotifications/com.iphoneislam.iphoneislam/Attachments/7ad0d5e3b6bedad1a45aa247f59357d2e85bc83d.jpeg, type: public.jpeg, options: <UNImageNotificationAttachmentOptions: 0x281c58200>>"
), badge: 5, sound: <UNNotificationSound: 0x2820de040>,, trigger: (null)>>>
```

But if the app in the background

```
Received Push Response: <UNNotificationResponse: 0x280512400; actionIdentifier: 1, notification: <UNNotification: 0x2805113a0; date: 2018-11-15 13:28:52 +0000, request: <UNNotificationRequest: 0x280a42e80; identifier: B6280F15-7635-4470-AD1C-CFBCBE55B886, content: <UNNotificationContent: 0x283165140; title: (null), subtitle: (null), body: NEWS BODY, summaryArgument: , summaryArgumentCount: 0, categoryIdentifier: 2075, launchImageName: , threadIdentifier: , attachments: (
    "<UNNotificationAttachment: 0x280a4a640; identifier: 4C28439E-8CB1-4FBB-8619-2038CFA3BA77200.jpg, family: Image, URL: file:///var/mobile/Library/UserNotifications/com.iphoneislam.iphoneislam/Attachments/7a2f379b94eeb2e87f72de45f51b98999c0f0ee2.jpeg, type: public.jpeg, options: <UNImageNotificationAttachmentOptions: 0x281c5da00>>"
), badge: 16, sound: <UNNotificationSound: 0x2820b3660>,, trigger: <UNPushNotificationTrigger: 0x28062c650; contentAvailable: NO, mutableCont
```

And because I ask for the user info to get the news ID, I get nothing so that why it was not working
`[self HandleActionsFromNotification:response.notification.request.content.userInfo withIdentifier:response.actionIdentifier];`

**Do you have any idea why I do not get (response.notification.request.content.userInfo) or (trigger: (null)) if the app in the foreground and user click one of the actions buttons? and how can I get the userinfo in the foreground?**


I know I took time in this issue to understand what is going on but this is real issue and I guess it will face others not only me.

**Comment by wfhm** [comment]
@iTarek 

When a push is received in foreground, its userinfo (response.notification.request.content.userInfo) is different from the one received in background:

foreground:
```
{
    "pw_push" =     {
        aps =         {
            alert = sdfsdf;
            badge = 0;
            category = 7630;
            sound = default;
        };
        p = "3,g";
    };
}
```

background:
```
{
    aps =     {
        alert = sdfsdf;
        badge = 0;
        category = 7630;
        sound = default;
    };
    p = "3,b";
}
```
It is a default behavior of our sdk, and there is a reason for it (was done this way to fix the issue with tapping a push in Notification Center). Therefore, you need to take into account that a push might be received with a pw_push key in userinfo.
