### ISSUE TITLE
 [iOS] bitcode bundle could not be generated because libPushwooshPlugin.a was built without full bitcode #45 

### ISSUE THREAD

**Issue by lorenc-tomasz** [Pushwoosh/pushwoosh-ios-sdk#75]
On 5.11.0:

bitcode bundle could not be generated because '.../libPushwooshPlugin.a(PWGeozonesManager.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '../libPushwooshPlugin.a' for architecture armv7

Connected with: https://github.com/Pushwoosh/pushwoosh-react-native-plugin/issues/45

**Comment by wfhm** [comment]
@lorenc-tomasz fixed with the latest release.
