### ISSUE TITLE
Swift 5.0 Binary

### ISSUE THREAD

**Issue by satindar** [Pushwoosh/pushwoosh-ios-sdk#76]
Is there a target date for releasing a Swift 5 binary? Thanks.

**Comment by wfhm** [comment]
Pushwoosh iOS SDK is Obj-C based, so when adding it to a Swift project, Swift interfaces are created automatically. Therefore, you do not need to do anything to support this particular Swift version. 

Also, both [the sample app](https://github.com/Pushwoosh/pushwoosh-ios-sdk/tree/master/Samples) and the code in [the integration guide](https://www.pushwoosh.com/platform-docs/pushwoosh-sdk/ios-push-notifications/setting-up-pushwoosh-ios-sdk) are compiling just fine with Swift 5.

**Comment by satindar** [comment]
@wfhm sorry, my mistake. i was getting a build error using carthage but it was from a different library 🙃
