### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by frederic-c-dcode** [Pushwoosh/pushwoosh-ios-sdk#77]
Dependency "pushwoosh-ios-sdk" has no shared framework schemes for any of the platforms: iOS

**Comment by wfhm** [comment]
@frederic-c-dcode  Hi,

Checking it.

**Comment by wfhm** [comment]
@frederic-c-dcode 

Could you please provide the following information?

* Carthage version
* your  cartfile contents
* the Terminal command you run

**Comment by wfhm** [comment]
@frederic-c-dcode any news on this one?

**Comment by wfhm** [comment]
Closed until there is more info on the issue.

**Comment by frederic-c-dcode** [comment]
Sorry for the delay. I had time to check again. When doing `carthage update`, it still says :
```
*** Skipped building pushwoosh-ios-sdk due to the error:
Dependency "pushwoosh-ios-sdk" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Pushwoosh/pushwoosh-ios-sdk/issues/new
```

I know you dont provide the source code to compile, but there should be a way to tell so in your carthage configuration ?
