### ISSUE TITLE
Crash on IOS 12.2

### ISSUE THREAD

**Issue by AmirTensera** [Pushwoosh/pushwoosh-ios-sdk#78]
Date/Time:           2019-04-07 12:00:38.9290 +0300
Launch Time:         2019-04-07 12:00:34.3381 +0300
OS Version:          iPhone OS 12.2 (16E227)
Baseband Version:    2.03.06
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000010
VM Region Info: 0x10 is not in any region.  Bytes before following region: 4305453040
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                 0000000100a00000-0000000101100000 [ 7168K] r-x/r-x SM=COW  ...<Appname>.app/<Appname>

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [1498]
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   Security                      	0x00000001b5cf9d98 SecKeyGetBlockSize + 0
1   <Appname>                          	0x0000000100d7c830 +[PWRSAManager processData:withKey:mode:error:] + 80
2   <Appname>                          	0x0000000100d97b88 -[PWSetAttributesRequest requestDictionary] + 764
3   <Appname>                          	0x0000000100d7d78c -[PWRequestManager sendRequestInternal:completion:] + 228
4   <Appname>                          	0x0000000100d7d284 -[PWRequestManager sendRequest:completion:] + 268
5   <Appname>                          	0x0000000100d9648c -[PWDataManager sendAttributes] + 340
6   Foundation                    	0x00000001b5a98f68 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
7   Foundation                    	0x00000001b59a5420 -[NSBlockOperation main] + 72
8   Foundation                    	0x00000001b59a4908 -[__NSOperationInternal _start:] + 740
9   Foundation                    	0x00000001b5a9acec __NSOQSchedule_f + 272
10  libdispatch.dylib             	0x00000001b4a561cc _dispatch_block_async_invoke2 + 104
11  libdispatch.dylib             	0x00000001b4a757d4 _dispatch_client_callout + 16
12  libdispatch.dylib             	0x00000001b4a559e4 _dispatch_main_queue_callback_4CF$VARIANT$armv81 + 1008
13  CoreFoundation                	0x00000001b4fc5ec0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
14  CoreFoundation                	0x00000001b4fc0df8 __CFRunLoopRun + 1924
15  CoreFoundation                	0x00000001b4fc0354 CFRunLoopRunSpecific + 436
16  GraphicsServices              	0x00000001b71c079c GSEventRunModal + 104
17  UIKitCore                     	0x00000001e1577b68 UIApplicationMain + 212
18  <Appname>                          	0x0000000100a88b9c main + 560028 (main.m:17)
19  libdyld.dylib                 	0x00000001b4a868e0 start + 4

**Comment by wfhm** [comment]
@AmirTensera Fixed in 5.13.1.

**Comment by wfhm** [comment]
@AmirTensera Could you please specify whether a device is jailbroken or not? If yes, the crash is fixed in 5.13.1. Also, could you please share a reproducer project with us?

**Comment by wfhm** [comment]
@AmirTensera any news?

**Comment by wfhm** [comment]
Closed until there is more info on the issue.
