### ISSUE TITLE
GDPR iOS

### ISSUE THREAD

**Issue by andrey-lisovskiy** [Pushwoosh/pushwoosh-ios-sdk#79]
I am developing iOS app and want to get user consent prior to capturing [this information](https://imgur.com/cazmSy2)
I've tried to call `PWGDPRManager.shared().showGDPRConsentUI()` but don't see any dialog.

**Comment by wfhm** [comment]
Hi @andrey-lisovskiy ,

According to the log screenshot, you use Pushwoosh iOS SDK v4.2.0, and the GDPR compliance method was only added in 5.6.0 release. 

Also, the GDPR compliance functionality is shipped as a separate add-on. I have checked the account for your application and it is not included in your current package. Please [contact our support team](https://help.pushwoosh.com/hc/en-us/requests/new) if you would like to know more about it.
