### ISSUE TITLE
-[PWIInboxViewController loadView] on iOS 10.3.3 crashes

### ISSUE THREAD

**Issue by lucacasula91** [Pushwoosh/pushwoosh-ios-sdk#81]
Hi, we have found a problem with the **PWInboxViewController** that crash with **iOS 10.3.3**

`-[NSBundle(UINSBundleAdditions) loadNibNamed:owner:options:]`
`-[PWIInboxViewController loadView]`
`-[UIViewController loadViewIfRequired]`

Here below you can find the TXT of the stack
[PWIInboxViewController iOS 10.txt](https://github.com/Pushwoosh/pushwoosh-ios-sdk/files/3232347/PWIInboxViewController.iOS.10.txt)

**Comment by wfhm** [comment]
Hi @lucacasula91,

Could you please share a reproducer project with us? It would be really helpful if you could also attach its source code (or at least the fragment of your code in which you show Inbox). You can send it to our Support team with a link to this issue via email at help@pushwoosh.com.
