### ISSUE TITLE
Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by ert2aziz** [Pushwoosh/pushwoosh-ios-sdk#82]
We getting the warning emails from Apple every time we submit new version to App Store Connect.
As our app not using any UIWebView and we looked at the problem, and it turns out that PushWoosh using UIWebView in "PWInAppManager.h"  file.

**Apple warning:**
_ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information._
 
could you please have a look at this issue.

Thanks.

**Comment by wfhm** [comment]
Hi @ert2aziz,

Thank you for the information provided!

Sure, our developers are already looking into this.

I will provide you with an update as soon as there is any news, stay tuned!

**Comment by wfhm** [comment]
Hi @ert2aziz,

Thank you for the information provided!

Sure, we are already looking into this.

Please stay tuned for further updates on this mater

**Comment by wfhm** [comment]
Hi @ert2aziz,

This will be fixed in the nearest time. We will notify you as soon as the job is done. Stay tuned!

**Comment by nicolasgoutaland** [comment]
Hi,
do you have any update on this issue ?
Regards

**Comment by wfhm** [comment]
@nicolasgoutaland,

The fix is now in code review, so it should be delivered shortly.

**Comment by nicolasgoutaland** [comment]
Thanks for your quick answer

**Comment by wfhm** [comment]
@ert2aziz, @nicolasgoutaland,

We've just rolled out the new SDK version which now uses WKWebView instead of UIWebView, so you can start using it right away.
