### ISSUE TITLE
Version 5.19.1 still contain reference to UIWebView

### ISSUE THREAD

**Issue by frederic-c-dcode** [Pushwoosh/pushwoosh-ios-sdk#83]
Version 5.19.1 still contain reference to UIWebView which cause Apple to complain « ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs ».

With a grep command line, I can clearly identify that Pushwoosh 5.19.1 is the culprit.

**Comment by wfhm** [comment]
Hi @frederic-c-dcode,

May I ask you to provide us with the output of the command that points to the Pushwoosh 5.19.1 version?

Any detailed information would be appreciated!

**Comment by frederic-c-dcode** [comment]
`cd Pushwoosh.framework`
`grep -R "UIWebView" .`

will print `Binary file ./Pushwoosh matches`

Open binary file `Pushwoosh` inside the `Pushwoosh.framework ` folder and you will see tons of occurences of `UIWebView`.

Maybe you’re not using UIWebView any more, but Apple scans your builds and reject then if they contain forbidden API.

**Comment by wfhm** [comment]
Hey @frederic-c-dcode,

Thanks for the information provided!

Indeed, you are correct. Please note that we have already fixed this in the version 5.19.2

https://github.com/Pushwoosh/pushwoosh-ios-sdk/releases/tag/5.19.2
