### ISSUE TITLE
Push Notifications not received on iOS 13

### ISSUE THREAD

**Issue by sharjeelnisar1** [Pushwoosh/pushwoosh-ios-sdk#85]
I am using PushWoosh via CocoaPods on iOS.
My app is not receiving push notifications when installed on iOS 13. It's successfully receiving push notifications on iOS 12 and even when my app was installed on iOS 12 and iOS version was later updated to 13.1.3.
My customers are getting affected. Please fix this issue as soon as possible.

**Comment by wfhm** [comment]
Hi @sharjeelnisar1,

Could you please specify the version of the Pushwoosh-iOS SDK you are using in your app at the moment?

**Comment by sharjeelnisar1** [comment]
HI,

 I am using PushWoosh via CocoaPods and I've updated my CocoaPods via
following:

 pod repo update
 pod install

Regards,

*Sharjeel Nisar*

**Comment by wfhm** [comment]
Solved via internal communication. The issue was not related to the iOS SDK.
