### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by ellited** [Pushwoosh/pushwoosh-ios-sdk#86]
Could you please add support Swift Package Manager?  
Right now it's not possible to use Pushwoosh SDK with SPM. Xcode returns error: 
`https://github.com/Pushwoosh/pushwoosh-ios-sdk/ has no Package.swift manifest`.

There is some docs about  Package.swift manifest: https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html

**Comment by wfhm** [comment]
Hi @ellited,

Let me consult my team regarding the possibility of adding this feature.

I will notify you as soon as there is any news

**Comment by wfhm** [comment]
Hi @ellited,

We have performed a research and as a result, I am afraid that we are not able to add support for Swift Package Manager. The ting is that that it is not possible to add a compiled library(Pushwoosh SDK) via Swift Package Manager. It works only with open-source libraries.

https://forums.swift.org/t/distributing-binary-closed-source-libraries/23737

**Comment by ellited** [comment]
@wfhm Ok, thanks for answer

**Comment by rextremotabaresDtt** [comment]
Any chance you could reconsider adding support to SPM? 
There has been improvements on [https://developer.apple.com/videos/play/wwdc2020/10147/](distributing binary frameworks with Swift Package Manager) so it should be feasible now.
