### ISSUE TITLE
Unexpected calling of PWMessagingDelegate method 'onMessageOpened'

### ISSUE THREAD

**Issue by apurv7** [Pushwoosh/pushwoosh-ios-sdk#89]
This issue occurs when my app is in the Background state(not in the killed state). Then whenever I receive a notification, both of the **_PWMessagingDelegate_** methods: **_onMessageReceived_** and _**onMessageOpened**_ are called, when ideally only  _**onMessageReceived**_ should be called as the user did not tap on the notification.

Below is the code: 

`func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        //initialization code
        //set custom delegate for push handling, in our case AppDelegate
        Pushwoosh.sharedInstance()?.delegate = self;
        
        //register for push notifications!
        Pushwoosh.sharedInstance()?.registerForPushNotifications()
        
        return true
    }
    
    //handle token received from APNS
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Pushwoosh.sharedInstance()?.handlePushRegistration(deviceToken)
    }
    
    //handle token receiving error
    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        Pushwoosh.sharedInstance()?.handlePushRegistrationFailure(error);
    }
    
    //this is for iOS < 10 and for silent push notifications
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        Pushwoosh.sharedInstance()?.handlePushReceived(userInfo)
        completionHandler(.noData)
    }
    
    //this event is fired when the push gets received
    func pushwoosh(_ pushwoosh: Pushwoosh!, onMessageReceived message: PWMessage!) {
        print("onMessageReceived: ", message.payload.description)
    }
    
    //this event is fired when user taps the notification
    func pushwoosh(_ pushwoosh: Pushwoosh!, onMessageOpened message: PWMessage!) {
        print("onMessageOpened: ", message.payload.description)
    }`

**Comment by wfhm** [comment]
Hello @apurv7,

Checking it.

**Comment by wfhm** [comment]
@apurv7 

> This issue occurs when my app is in the Background state(not in the killed state). Then whenever I receive a notification, both of the PWMessagingDelegate methods: onMessageReceived and onMessageOpened are called, when ideally only onMessageReceived should be called as the user did not tap on the notification.

I was unable to reproduce the issue so far - when a push is received in background, it does not trigger onMessageOpened. What plugin version are you using? Also, by any chance is it possible to share a reproducer project with us (via Github or send it over the [Contact Us](https://www.pushwoosh.com/contact-us/) form)?

**Comment by apurv7** [comment]
@wfhm Can you share your AppDelegate's code along with delegate methods? That would help me to compare. I am currently using Pushwoosh -> 6.0.1.

**Comment by wfhm** [comment]
@apurv7,

I was using the sample app:

https://github.com/Pushwoosh/pushwoosh-ios-sdk/blob/master/Samples/iPhone-SWIFT/PushNotificationsApp/AppDelegate.swift

**Comment by elihaidv** [comment]
HI I have the same problem
Can you please tell me if you figured it out?
