### ISSUE TITLE
Getting push notification payload when user opens app manually after push has been received in the background.

### ISSUE THREAD

**Issue by apurv7** [Pushwoosh/pushwoosh-ios-sdk#90]
**_launchOptions_** key is not nil when the notification is received when the app is in killed state and the user opens the app through the app icon(when the device is on). Hence, the app is not able to differentiate if it's opened via notification tap or manually. Happening for iOS 13.

```javascript
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
  // launchOptions is not nil when app is opened manually after push is received in killed state
}
```

**Comment by wfhm** [comment]
@apurv7,

Did you try using the launchNotification property?

**Comment by apurv7** [comment]
No, didn't find any documentation for that. Can you please give an example.

**Comment by wfhm** [comment]
@apurv7,

You can call it in your app whenever you need to access the payload of a notification used to open the app (if the app was opened in response to a push notification, this value will be stored until the next launch:

    NSDictionary *launchNotification = [Pushwoosh sharedInstance].launchNotification;

**Comment by apurv7** [comment]
@wfhm,

That's okay, but my issue is that _**launchOptions**_ should ideally be **_nil_** when the app is launched via app icon. Right now we can't replace our logic for _**launchOptions**_. 

Can you please tell why it's not nil when the app is opened manually. Due to this, our redirection logic is running even when the user is not tapping on the notification.

**Comment by wfhm** [comment]
@apurv7,

This is really strange. Pushwoosh SDK does not control launchOptions payload at all, and, actually, it should be controlled by iOS itself. Could you please let me know what is the value of launchOptions in the case when you open the app directly and there is a push notification available?

**Comment by apurv7** [comment]
@wfhm,

The values are the same. Ideally, if the app is opened via app icon, _launchOptions_ should be nil even if there are notifications received. But I receive the notification data when I parse _launchOptions_ . Below is the code for getting notification payload.

    let notification = launchOptions?[UIApplication.LaunchOptionsKey.remoteNotification]

This value should be nil if app is opened via app icon.

**Comment by wfhm** [comment]
@apurv7,

Can you share the exact payload you receive in launchOptions?
