### ISSUE TITLE
Dependency "pushwoosh-ios-sdk" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by ashleymills** [Pushwoosh/pushwoosh-ios-sdk#92]
```
carthage update --platform iOS
```

fails for release 6.0.12 with message
> Dependency "pushwoosh-ios-sdk" has no shared framework schemes for any of the platforms: iOS

this works fine for release 6.0.11

**Comment by wfhm** [comment]
@ashleymills,

Checking it.

**Comment by wfhm** [comment]
@ashleymills fixed (there was an issue with rolling out the last release).
