### ISSUE TITLE
Crash on Pushwoosh.sharedInstance()?.setEmail(email: String!)

### ISSUE THREAD

**Issue by bb-git** [Pushwoosh/pushwoosh-ios-sdk#95]
When setting the email with this method and then deallocating the calling view controller, a crash might happen, when the caller is already deallocated before completing. As this method does require a completion handler, it should be within the responsibilty of the callee to retain the object until the execution is completed.

**Comment by wfhm** [comment]
@bb-git,

Can you share the crash log with us? Also, what is the version of Pushwoosh iOS SDK affected by the issue?

**Comment by bb-git** [comment]
I'm using the latest SDK version.
![Bildschirmfoto 2021-02-06 um 11 54 58](https://user-images.githubusercontent.com/7348507/107115003-51087000-6872-11eb-8d1e-cebe418eed7a.png)

**Comment by wfhm** [comment]
@bb-git,

Thanks, checking it now.

**Comment by wfhm** [comment]
@bb-git,

Can you share a snippet of how and where exactly you use the `Pushwoosh.sharedInstance()?.setEmail(email: String!)` method in your code?
