### ISSUE TITLE
Start using Nullability annotations so Swift apps don't have to deal unnecessary optionals

### ISSUE THREAD

**Issue by Noobish1** [Pushwoosh/pushwoosh-ios-sdk#96]
Here's a guide: https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/designating_nullability_in_objective-c_apis

**Comment by wfhm** [comment]
@Noobish1 hi,

Since Pushwoosh SDK is used in all our cross-platform plugins, we will have to research that all the frameworks support nullability annotations to make sure it won't break anything. I will update this thread once there is more news.

**Comment by akiselev-pushwoosh** [comment]
Hey @Noobish1,
Sorry for the slow reply. Just wanted to let you know that the feature you mentioned was added in release 6.4.4. If you want to use it and any other new stuff, you might want to update to the latest version of SDK. Let me know if you have any other questions.
