### ISSUE TITLE
Can't checkout Pushwoosh with Carthage

### ISSUE THREAD

**Issue by dungi** [Pushwoosh/pushwoosh-ios-sdk#97]
Following error when checking pushwoosh with:
`carthage update --platform iOS --no-use-binaries`

Dependency "pushwoosh-ios-sdk" has no shared framework schemes for any of the platforms: iOS

Carthage file:
github "Pushwoosh/pushwoosh-ios-sdk" == 6.2.0

**Comment by wfhm** [comment]
@dungi,

Checking it.

**Comment by wfhm** [comment]
@dungi,

It seems the error is thrown only when `--no-use-binaries` flag is added. I will look into it, meanwhile could you please let me know if you can use `carthage update` without this flag?

**Comment by dungi** [comment]
Even without --no-use-binaries it doesn't work. I added this, cause I found that in some other closed bug-ticket here.

**Comment by wfhm** [comment]
@dungi,

Can you specify your Xcode and Carthage versions?


> Even without --no-use-binaries it doesn't work.


Does it throw the same error when removing the flag?

**Comment by dungi** [comment]
Yes. Both should be the latest Version. I just update them yesterday.

**Comment by dungi** [comment]
As long as SPM is not supported completly, I tried to use Carthage, cause I'm not a fan of CocoaPods. But maybe I will use the xcframework you posted today, cause I can't get Carthage work correctly.

**Comment by wfhm** [comment]
@dungi,

Any luck with the new xcframeworks? If you still have to use Carthage and you still get the same error, could you please share a reproducer project?

**Comment by dungi** [comment]
Yeah the xcframework is good to go, safe to try :) - But very strange, that Carthage didn't worked... I will check this later, If we will use Carthage in our project
