### ISSUE TITLE
Error sending event: Pushwoosh User Id is missing

### ISSUE THREAD

**Issue by bb-git** [Pushwoosh/pushwoosh-ios-sdk#98]
Can you please explain what's going wrong? There is no documentation explaining what this error means.

**Comment by wfhm** [comment]
@bb-git could you please provide a bit more detail on the issue? When and where exactly do you get this error? What are the steps to reproduce it?

**Comment by bb-git** [comment]
Launch app and send the event on the first viewcontroller in viewdidload()

**Comment by wfhm** [comment]
@bb-git,

Can you share the entire console log starting with your app being opened? Pushwoosh SDK always sets a default User ID (equal to its HWID), so this is quite a weird error message.

**Comment by bb-git** [comment]
I'm debugging remotely, so this is the only message I got. Is sending events only possilbe are registerForPushNotifications? Probably it's not completed.

**Comment by bb-git** [comment]
Thanks, this is already helping. Is there a callback, when the initialization is finished? I'm starting with provisional messages now, so I want to send the event in the earliest moment possible.

**Comment by wfhm** [comment]
@bb-git,

No, there is no such а callback. Our SDK swizzles didFinishLaunchingWithOptions method of your AppDelegate and initialization starts when didFinishLaunchingWithOptions is called. When viewDidLoad() of your ViewController is called, SDK initialization should have already finished, so this is really strange. Could it be that there are other libraries that swizzle didFinishLaunchingWithOptions()? Also, are the other methods of our SDK work as expected? Can you receive pushes on that test device?

**Comment by bb-git** [comment]
so far I know, there are no other libraries doing this. The other methods seem to work, but I'm not always receiving the push, even if it look like I'm entering the journey, maybe the iphone has a frequency capping? How can I Initialize the SDK on my own, is it enough to remove the key from the plist and call the initialize method on my own?

**Comment by wfhm** [comment]
@bb-git


> How can I Initialize the SDK on my own, is it enough to remove the key from the plist and call the initialize method on my own?


After you add our SDK to your project, it will initialize when your app is launched automatically - we swizzle didFinishLaunchingWithOptions method of the AppDelegate, so when it is called, SDK initialization starts. Removing your App ID from info.plist will just result in initialization failure.

Also, initializing SDK manually might not help, as we don't even know yet what is causing the issue. It is essential to proceed with the investigation to obtain the logs to know what is happening on a device. As you are debugging remotely and you cannot obtain them on your own, could it be an option to share the build with us so we could try it on our side? You can share it via the Contact Us form.

**Comment by bb-git** [comment]
I moved sending the event to the callback from registerForPushNotifications(). This way sending the event does not fail anymore. I will test further and see if push messages are always being sent.

**Comment by wfhm** [comment]
@bb-git,

That's good news to hear. I will close the issue for now, however, please feel free to reopen it shall any issues appear during your tests.
