### ISSUE TITLE
sendAppOpen method no longer necessary?

### ISSUE THREAD

**Issue by joe-at-startupmedia** [Pushwoosh/pushwoosh-ios-sdk#99]
In upgrading to the latest pushwoosh library (6.22) I've seen that the  PushNotificationManager class is deprecated.
https://github.com/Pushwoosh/pushwoosh-ios-sdk/blob/master/Documentation/PushNotificationManager.md

The Pushwoosh class however has no method `sendAppOpen`. Is this no longer necessary to call?
https://github.com/Pushwoosh/pushwoosh-ios-sdk/blob/master/Documentation/PushNotificationManager.md#1a4cd6ec2302bebac9ffcb229eae5d6a59

**Comment by wfhm** [comment]
@joe-at-startupmedia,

Yes, it now automatically fires when an app is opened, there is no need to manually call it.
